[build]
target = "index.html"
dist = "docs"  # Usa "docs" per GitHub Pages
release = true
minify = "on_release"
watch = ["src", "public", "index.html"]
public_url = "/wasm-knowledge-chatbot-rs/"  # Corretto il nome del repository

# Ottimizzazioni per WebAssembly
[build.wasm]
opt_level = "z"  # Massima ottimizzazione per le dimensioni
debug = false    # Disabilita i simboli di debug

[build.wasm.bindgen]
demangle = true
weak_refs = true

# Configurazione del server di sviluppo
[serve]
port = 8080
enabled = false  # Disabilitato per le build di produzione

# Hooks
[[hooks]]
# Crea un file .nojekyll nella cartella di output
stage = "post_build"
command = "bash"
command_arguments = ["-c", "touch docs/.nojekyll"]