[build]
target = "index.html"
dist = "docs"  # Use "docs" for GitHub Pages deployment
release = true
minify = "on_release"
watch = ["src", "public", "index.html"]
public_url = "/wasm-knowledge-chatbot-rs/"  # Must match the GitHub Pages repo name

# WebAssembly optimizations for production bundle size
[build.wasm]
opt_level = "z"  # Maximum size optimization
debug = false    # Disable debug symbols

[build.wasm.bindgen]
demangle = true
weak_refs = true

# Dev server configuration (disabled for production builds)
[serve]
port = 8080
enabled = false  # Keep disabled when building for deployment

# Hooks
[[hooks]]
# Create a .nojekyll file in the output folder (required for GitHub Pages)
stage = "post_build"
command = "bash"
command_arguments = ["-c", "touch docs/.nojekyll"]

# -----------------------------
# How to build with this config
# -----------------------------
# Use the following command to build using this specific configuration file:
#
#   trunk build --config Trunk.Dep.toml
#
# This will generate the production site into the `docs/` directory, ready for GitHub Pages.